// BoxRFID – Filament Tag Manager
//
// Author: Tinkerbarn
// License: CC BY-NC-SA 4.0 (SPDX-License-Identifier: CC-BY-NC-SA-4.0)

import 'dart:io';
import 'package:path_provider/path_provider.dart';

/// Parses and generates `official_filas_list.cfg` files compatible with the
/// QIDI Box firmware and the BoxRFID Electron desktop app.
class CfgService {
  CfgService._();

  /// Parses the content of an `official_filas_list.cfg` file.
  ///
  /// Returns a map with `'materials'` (`Map<int,String>`) and
  /// `'manufacturers'` (`Map<int,String>`) entries.
  /// Returns `null` if no materials are found (invalid / unrecognized format).
  ///
  /// Materials must have codes in 1–255; manufacturers in 0–20.
  static Map<String, Map<int, String>>? parseCfg(String content) {
    final materials = <int, String>{};
    final manufacturers = <int, String>{};

    String section = '';
    int? filaNum;

    for (final rawLine in content.split(RegExp(r'\r?\n'))) {
      final line = rawLine.trim();
      if (line.isEmpty || line.startsWith('#') || line.startsWith(';')) {
        continue;
      }

      if (line.startsWith('[') && line.endsWith(']')) {
        final secName =
            line.substring(1, line.length - 1).trim().toLowerCase();
        section = secName;
        filaNum = null;
        final match = RegExp(r'^fila(\d{1,3})$').firstMatch(secName);
        if (match != null) {
          filaNum = int.tryParse(match.group(1)!);
        }
        continue;
      }

      final eqIdx = line.indexOf('=');
      if (eqIdx == -1) continue;
      final key = line.substring(0, eqIdx).trim().toLowerCase();
      final val = line.substring(eqIdx + 1).trim();

      if (filaNum != null && section.startsWith('fila')) {
        if (key == 'filament' && val.isNotEmpty) {
          final code = filaNum;
          if (code >= 1 && code <= 255) {
            materials[code] = val;
          }
        }
      } else if (section == 'vendor_list' || section == 'vendor list') {
        if (val.isNotEmpty) {
          final code = int.tryParse(key);
          if (code != null && code >= 0 && code <= 20) {
            manufacturers[code] = val;
          }
        }
      }
    }

    if (materials.isEmpty) return null;

    return {'materials': materials, 'manufacturers': manufacturers};
  }

  /// Generates `official_filas_list.cfg` content from [materials] and
  /// [manufacturers], sorted by code.
  ///
  /// The output is compatible with the QIDI Box firmware parser and the
  /// BoxRFID Electron desktop app.
  static String generateCfg(
    Map<int, String> materials,
    Map<int, String> manufacturers,
  ) {
    final buffer = StringBuffer();
    buffer.writeln('# official_filas_list.cfg');
    buffer.writeln('# Generated by BoxRFID app');
    buffer.writeln();

    final sortedMaterials = materials.entries.toList()
      ..sort((a, b) => a.key.compareTo(b.key));
    for (final entry in sortedMaterials) {
      buffer.writeln('[Fila${entry.key}]');
      buffer.writeln('filament=${entry.value}');
      buffer.writeln();
    }

    buffer.writeln('[Vendor_List]');
    final sortedManufacturers = manufacturers.entries.toList()
      ..sort((a, b) => a.key.compareTo(b.key));
    for (final entry in sortedManufacturers) {
      buffer.writeln('${entry.key}=${entry.value}');
    }

    return buffer.toString();
  }

  /// Writes [content] to a temporary file named `official_filas_list.cfg`
  /// and returns the resulting [File].
  static Future<File> writeTempCfgFile(String content) async {
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/official_filas_list.cfg');
    await file.writeAsString(content, flush: true);
    return file;
  }
}
